coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "packages/**/example/**"
  - "packages/**/test/**"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.mocks.dart"
