name: flutter_use

packages:
  - packages/**
  - packages/**/example/*

ide:
  intellij: true
  vscode: true

scripts:
  upgrade:
    run: melos exec -- flutter pub upgrade

  get:
    run: melos exec -- flutter pub get

  analyze: melos exec -- dart analyze .

  format: dart format .

  test:
    run: |
      melos exec -c 8 -- flutter test
    packageFilters:
      scope: flutter_use
