# Analysis options for battery example app
# Inherits from package rules but with relaxed settings for demo purposes

include: ../analysis_options.yaml

linter:
  rules:
    # Relax some rules for example apps
    public_member_api_docs: false # Don't require docs for example code
    avoid_print: false # Allow print statements in example apps for debugging
