name: Dart CI

on:
  pull_request: {}
  push:
    branches:
      - "main"

jobs:
  build:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set environment
        run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Get dependencies
        run: |
          dart pub global activate melos
          melos run get

      - name: Run tests with coverage
        run: |
          melos run test-coverage

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          directory: ./packages/basic/coverage
          flags: unittests
          name: flutter-use-coverage
          fail_ci_if_error: false

      - name: Check for any formatting and statically analyze the code.
        run: |
          melos run format-check
          melos run analyze
